server.port=8090

# ===============================
# THYMELEAF
# ===============================
spring.thymeleaf.cache=false

# ===============================
# DATABASE - SQL SERVER
# ===============================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=webst2_restapi;encrypt=false;trustServerCertificate=true;sslProtocol=TLSv1.2;characterEncoding=UTF-8
spring.datasource.username=sa
spring.datasource.password=YOUR_PASSWORD_HERE
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Thu muc luu file upload (Category icon + Product image)
storage.location=uploads

# ===============================
# SWAGGER3 (springdoc)
# ===============================
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
